[package]
name = "imperator-save"
version = "0.4.2"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
exclude = ["/assets/*", "/fuzz/*"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rakaly/imperator-save.git"
description = "Ergonomically work with Imperator Rome saves (debug and ironman)"
keywords = ["imperator", "ironman"]
categories = ["parsing"]

[features]
serialize = []

[dependencies]
jomini = { version = "0.27.0", features = ["json"] }
serde = { version = "1", features = ["derive"] }
flate2 = { version = "1.0.29", default-features = false, features = ["zlib-rs"] }
rawzip = "0.0.6"
thiserror = "1"

[dev-dependencies]
attohttpc = "0.26"

# We override the test profile so that our tests run in a tolerable time as
# some of the asset files are heavyweight and can take a significant amount of
# time. Here is some timing data recorded to run one test:
#
# cargo test                 0m15.037s
# cargo test (opt-level=3)   0m9.644s
# cargo test (+lto=thin)     0m0.907s
# cargo test --release       0m0.620s
[profile.test]
opt-level = 3
lto = "thin"

[profile.bench]
lto = true
codegen-units = 1

[profile.release]
lto = true
codegen-units = 1
